### ISSUE TITLE
About downloading QVI-960 dataset

### ISSUE THREAD

**Issue by lhao0301** [xuxy09/QVI#1]
Thanks for your nice work!

The QVI-960 dataset in dropbox is not accessible due to my unstable/terrible network.

Can u share one copy of the dataset in Baidu netdisk.

**Comment by xuxy09** [comment]
It seems the largest file allowed in Baidu is 4GB while the QVI-960 is more than 20GB. I would recommend use some VPN to download from Dropbox.

**Comment by lhao0301** [comment]
Actually, I have tried it for several times with my VPN.
It takes about ~10h to finish it and often lose the connection due to my poor network .

Zipping the dataset into multiple files with splitting may be one alternative.
