### ISSUE TITLE
About QVI-960 dataset

### ISSUE THREAD

**Issue by rastaman7** [xuxy09/QVI#3]
Thank you for sharing your work on github.
I have a question about the QVI-960 dataset.
In the paper, it saids "The final training dataset consists of 173 video clips of different scenes and 36926 frames in total",but the dataset I downloaded from github seems to contain more frames.
Could you tell me the reason?
Also, how many videos were used to create the QVI-960 dataset on github?

**Comment by weiMytian** [comment]
> Thank you for sharing your work on github. I have a question about the QVI-960 dataset. In the paper, it saids "The final training dataset consists of 173 video clips of different scenes and 36926 frames in total",but the dataset I downloaded from github seems to contain more frames. Could you tell me the reason? Also, how many videos were used to create the QVI-960 dataset on github?
Hi, when I downloaded the qvi-960 dataset, there were many abnormal interruptions. Can you share your download link of the downloaded dataset? Thank you very much!

**Comment by weiMytian** [comment]
> Thank you for sharing your work on github. I have a question about the QVI-960 dataset. In the paper, it saids "The final training dataset consists of 173 video clips of different scenes and 36926 frames in total",but the dataset I downloaded from github seems to contain more frames. Could you tell me the reason? Also, how many videos were used to create the QVI-960 dataset on github?

Hi, when I downloaded the qvi-960 dataset, there were many abnormal interruptions. Can you share your download link of the downloaded dataset? Thank you very much!

**Comment by weiMytian** [comment]
Hi, author, thank you for your sharing. I had several abnormal interruptions when downloading the qvi-960 dataset. Do you have any other download links to share? Thank you very much!

**Comment by xuxy09** [comment]
> Hi, author, thank you for your sharing. I had several abnormal interruptions when downloading the qvi-960 dataset. Do you have any other download links to share? Thank you very much!

As the dataset is too large, we could not afford to buy another cloud service to store it. But usually Dropbox is quite stable according to my experience. Please try "wget https://www.dropbox.com/s/4i6ff6o62sp2f69/QVI-960.zip"
