### ISSUE TITLE
about the pretrained model

### ISSUE THREAD

**Issue by RIA1159** [xuxy09/QVI#4]
I read this paper on NIPS recently and thank you for sharing your work on github.
However, when I tried to run this code, I find the I can't download these pretrained models, perhaps these download links are dead :(
Could you please check this links ?(or could you release a google drive link of these models)
I would be very thankful if you could respond my issues!!
Have a nice day.

**Comment by xuxy09** [comment]
Hi, I have checked the links and they seem fine to me. Can you try again?

**Comment by RIA1159** [comment]
Thanks for your reply, it seems that dropbox is baned for Chinese area, I've download the models by move my ip address to US. Anyway, thanks for your respond!
